- name: install citus
  hosts: all
  become: True
  tasks:
    - name: Add Citus repository for package manager
      script: deb.sh

    - name: install postgres
      apt: name=postgresql-11-citus-8.3 update_cache=yes

    - name: preload citus extension
      command: pg_conftool 11 main set shared_preload_libraries citus
      become: True
      register: out

    - debug: var=out.stdout_lines

    - name: pg listen on all IP interfaces
      command: pg_conftool 11 main set listen_addresses '*'
      become: True
      register: out

    - debug: var=out.stdout_lines

    - name: copy pg_hga.conf
      copy:
        src: pg_hga.conf
        dest: /etc/postgresql/11/main/pg_hba.conf
      become: True
      register: out

    - debug: var=out.stdout_lines

    - name: restart service postgresql
      service:
        name: postgresql
        state: restarted
      register: out

    - debug: var=out.stdout_lines

    - name: add the citus extension
      command: psql -c "CREATE EXTENSION citus;"
      become: True
      become-user: postgres
      register: out

    - debug: var=out.stdout_lines